Update sanic version in requirements.txt
Sanic example doesn't work because of the server version specified in requirements (0.3.1).

Traceback (most recent call last):
  File "app.py", line 23, in <module>
    @app.listener('before_server_start')
AttributeError: 'Sanic' object has no attribute 'listener'

The code starts to work from 0.7 sanic version.